// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

// GENERATED by scripts/curve_model.py -- do not edit by hand.
import {Test} from "forge-std/Test.sol";
import {CurveMath} from "../contracts/CurveMath.sol";

contract CurveMathCasesTest is Test {
    function test_case0() public pure {
        uint256 P = 5000000000000000000;
        uint256 T = 1000000000000000000000000000;
        uint256 R = 0;
        uint256 k = P * T;
        uint256 out;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 18918154818964005668980);
        assertEq(out, 999735773445398797555646073);
        R += 18918154818964005668980;
        (out, T) = CurveMath.quoteOut(k, P + R, T, 281102467165648812666152701);
        assertEq(out, 18905384414322682803559);
        R -= 18905384414322682803559;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 2007230302318669857300);
        assertEq(out, 278897558779795506238968722);
        R += 2007230302318669857300;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 4577185771370887202230);
        assertEq(out, 1711810072941214072918363);
        R += 4577185771370887202230;
        assertGe((P + R) * T, k);
    }

    function test_case1() public pure {
        uint256 P = 123456000000000000000000;
        uint256 T = 1000000000000000000000000000;
        uint256 R = 0;
        uint256 k = P * T;
        uint256 out;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 5542888465423328720182);
        assertEq(out, 42968497879026580502146412);
        R += 5542888465423328720182;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 9163679046008638820615);
        assertEq(out, 63475438248717310172655666);
        R += 9163679046008638820615;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 5381840272473079199784);
        assertEq(out, 33501660458272778770780081);
        R += 5381840272473079199784;
        assertGe((P + R) * T, k);
    }

    function test_case2() public pure {
        uint256 P = 123456000000000000000000;
        uint256 T = 1000000000000000000000000000;
        uint256 R = 0;
        uint256 k = P * T;
        uint256 out;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 13115992846585354338042);
        assertEq(out, 96037207726176102092302056);
        R += 13115992846585354338042;
        (out, T) = CurveMath.quoteOut(k, P + R, T, 36593756100814626683493594);
        assertEq(out, 5313537187175574936197);
        R -= 5313537187175574936197;
        (out, T) = CurveMath.quoteOut(k, P + R, T, 25685832889868824551689322);
        assertEq(out, 3489272280768357542742);
        R -= 3489272280768357542742;
        (out, T) = CurveMath.quoteOut(k, P + R, T, 367534145513912183870437);
        assertEq(out, 48581684180386048369);
        R -= 48581684180386048369;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 8533870688758642845240);
        assertEq(out, 60540574414179317118539760);
        R += 8533870688758642845240;
        (out, T) = CurveMath.quoteOut(k, P + R, T, 5422432868070143837825958);
        assertEq(out, 810573118329244836368);
        R -= 810573118329244836368;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 11503932297496245936094);
        assertEq(out, 71356885942229665698491068);
        R += 11503932297496245936094;
        assertGe((P + R) * T, k);
    }

    function test_case3() public pure {
        uint256 P = 5000000000000000000;
        uint256 T = 1000000000000000000000000000;
        uint256 R = 0;
        uint256 k = P * T;
        uint256 out;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 15739377223455986974589);
        assertEq(out, 999682426308196490895709437);
        R += 15739377223455986974589;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 14662170578904553970309);
        assertEq(out, 153135425660983159932534);
        R += 14662170578904553970309;
        (out, T) = CurveMath.quoteOut(k, P + R, T, 305837405311221185620794361);
        assertEq(out, 30390208031522735862583);
        R -= 30390208031522735862583;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 17735998980850648743786);
        assertEq(out, 305720190547307351139753883);
        R += 17735998980850648743786;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 11397104648299211998948);
        assertEq(out, 110123168185923623873657);
        R += 11397104648299211998948;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 8884745067417964511906);
        assertEq(out, 40069189210498815446073);
        R += 8884745067417964511906;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 3511352006195602175836);
        assertEq(out, 11110812169445920288790);
        R += 3511352006195602175836;
        assertGe((P + R) * T, k);
    }

    function test_case4() public pure {
        uint256 P = 5000000000000000000;
        uint256 T = 1000000000000000000000000000;
        uint256 R = 0;
        uint256 k = P * T;
        uint256 out;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 591288249748695429698);
        assertEq(out, 991614793680560969177238960);
        R += 591288249748695429698;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 3217809366794047117684);
        assertEq(out, 7074280249190150059662173);
        R += 3217809366794047117684;
        (out, T) = CurveMath.quoteOut(k, P + R, T, 283428284071036676851946785);
        assertEq(out, 3796537688644090880141);
        R -= 3796537688644090880141;
        (out, T) = CurveMath.quoteOut(k, P + R, T, 192396601775567598841992298);
        assertEq(out, 7080731252495683200);
        R -= 7080731252495683200;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 11342993338313969700425);
        assertEq(out, 476695418021099784609456471);
        R += 11342993338313969700425;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 2128950822219806786264);
        assertEq(out, 69540684313656969817349);
        R += 2128950822219806786264;
        (out, T) = CurveMath.quoteOut(k, P + R, T, 360962716292874519818175287);
        assertEq(out, 13468585727847957819480);
        R -= 13468585727847957819480;
        (out, T) = CurveMath.quoteOut(k, P + R, T, 119530891808675899187598179);
        assertEq(out, 3439688951128857682);
        R -= 3439688951128857682;
        assertGe((P + R) * T, k);
    }

    function test_case5() public pure {
        uint256 P = 5000000000000000000;
        uint256 T = 1000000000000000000000000000;
        uint256 R = 0;
        uint256 k = P * T;
        uint256 out;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 18660672158934459682593);
        assertEq(out, 999732128585703959573250467);
        R += 18660672158934459682593;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 5907175010408277318269);
        assertEq(out, 64394789648407555130188);
        R += 5907175010408277318269;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 18222976281577480171032);
        assertEq(out, 86642793754434168544643);
        R += 18222976281577480171032;
        assertGe((P + R) * T, k);
    }

    function test_case6() public pure {
        uint256 P = 5000000000000000000000;
        uint256 T = 1000000000000000000000000000;
        uint256 R = 0;
        uint256 k = P * T;
        uint256 out;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 5007900719456721381727);
        assertEq(out, 500394724112388590524894566);
        R += 5007900719456721381727;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 11889771133992021937513);
        assertEq(out, 271270499777039090055746587);
        R += 11889771133992021937513;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 11135709142234826085178);
        assertEq(out, 76972734161147168270578016);
        R += 11135709142234826085178;
        (out, T) = CurveMath.quoteOut(k, P + R, T, 749388146300501645845640464);
        assertEq(out, 27482452375047329038182);
        R -= 27482452375047329038182;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 11968662649689544151541);
        assertEq(out, 615355402329956941596476701);
        R += 11968662649689544151541;
        assertGe((P + R) * T, k);
    }

    function test_case7() public pure {
        uint256 P = 5000000000000000000000;
        uint256 T = 1000000000000000000000000000;
        uint256 R = 0;
        uint256 k = P * T;
        uint256 out;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 13184574954788289080031);
        assertEq(out, 725041689870049993874562171);
        R += 13184574954788289080031;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 18810416616651018917795);
        assertEq(out, 139804880229993616233729654);
        R += 18810416616651018917795;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 16700774217035031279550);
        assertEq(out, 42036218019662517789618516);
        R += 16700774217035031279550;
        (out, T) = CurveMath.quoteOut(k, P + R, T, 834547071940830628731377143);
        assertEq(out, 48305884893842291941299);
        R -= 48305884893842291941299;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 5027611015548423991126);
        assertEq(out, 447702308029834385473831095);
        R += 5027611015548423991126;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 7458068736155226882888);
        assertEq(out, 200250469174855828899773355);
        R += 7458068736155226882888;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 3345858011032630314748);
        assertEq(out, 44100491126480666709794829);
        R += 3345858011032630314748;
        assertGe((P + R) * T, k);
    }

    function test_case8() public pure {
        uint256 P = 5000000000000000000000;
        uint256 T = 1000000000000000000000000000;
        uint256 R = 0;
        uint256 k = P * T;
        uint256 out;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 17488564588350103739943);
        assertEq(out, 777664778009434080503882548);
        R += 17488564588350103739943;
        (out, T) = CurveMath.quoteOut(k, P + R, T, 323854694309602952625789407);
        assertEq(out, 13334239598483105549602);
        R -= 13334239598483105549602;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 1051522388094389757212);
        assertEq(out, 56274692719905311540620566);
        R += 1051522388094389757212;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 15384582012027612332900);
        assertEq(out, 294529678312468849841519240);
        R += 15384582012027612332900;
        (out, T) = CurveMath.quoteOut(k, P + R, T, 145955394001387391157092341);
        assertEq(out, 10942318294070937353983);
        R -= 10942318294070937353983;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 11056831947655487363200);
        assertEq(out, 146825822409195842701483942);
        R += 11056831947655487363200;
        (out, T) = CurveMath.quoteOut(k, P + R, T, 390360153112917768940683711);
        assertEq(out, 17156111768434085268861);
        R -= 17156111768434085268861;
        (out, T) = CurveMath.quoteOut(k, P + R, T, 230220530421327893024565293);
        assertEq(out, 2414583009375264639318);
        R -= 2414583009375264639318;
        assertGe((P + R) * T, k);
    }

    function test_case9() public pure {
        uint256 P = 5000000000000000000;
        uint256 T = 1000000000000000000000000000;
        uint256 R = 0;
        uint256 k = P * T;
        uint256 out;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 1484177743227907088227);
        assertEq(out, 996642442433257083112738214);
        R += 1484177743227907088227;
        (out, T) = CurveMath.quoteOut(k, P + R, T, 53510244429085491297225425);
        assertEq(out, 1401254527901828901392);
        R -= 1401254527901828901392;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 15556899152844673137899);
        assertEq(out, 56548207443564749730987586);
        R += 15556899152844673137899;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 15494025859761065980490);
        assertEq(out, 159023423768451088238818);
        R += 15494025859761065980490;
        assertGe((P + R) * T, k);
    }

    function test_case10() public pure {
        uint256 P = 5000000000000000000000;
        uint256 T = 1000000000000000000000000000;
        uint256 R = 0;
        uint256 k = P * T;
        uint256 out;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 331012243653170255172);
        assertEq(out, 62091818312226998642987214);
        R += 331012243653170255172;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 5380933130435452040118);
        assertEq(out, 471139557932967631380198457);
        R += 5380933130435452040118;
        (out, T) = CurveMath.quoteOut(k, P + R, T, 271373746210085859367180481);
        assertEq(out, 3938184371535932600052);
        R -= 3938184371535932600052;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 18148320251245443534166);
        assertEq(out, 537517071095118931105315042);
        R += 18148320251245443534166;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 15323386650449237746335);
        assertEq(out, 76387707399943297694364338);
        R += 15323386650449237746335;
        (out, T) = CurveMath.quoteOut(k, P + R, T, 698230920334535892387025635);
        assertEq(out, 34166207813145771819538);
        R -= 34166207813145771819538;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 10536892442963583228228);
        assertEq(out, 521556493227899781316240718);
        R += 10536892442963583228228;
        assertGe((P + R) * T, k);
    }

    function test_case11() public pure {
        uint256 P = 123456000000000000000000;
        uint256 T = 1000000000000000000000000000;
        uint256 R = 0;
        uint256 k = P * T;
        uint256 out;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 16722366535690954757288);
        assertEq(out, 119293489779917332755578743);
        R += 16722366535690954757288;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 2356738135753481427251);
        assertEq(out, 14561988948802854934619458);
        R += 2356738135753481427251;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 14716400101063884672402);
        assertEq(out, 81058234315866586269921213);
        R += 14716400101063884672402;
        (out, T) = CurveMath.tokensOut(k, P + R, T, 8716554750656437517858);
        assertEq(out, 41232316771657462392126675);
        R += 8716554750656437517858;
        assertGe((P + R) * T, k);
    }

}
