"""Integer model of CurveMath, and a generator for test/CurveMathCases.t.sol.

Every division of k rounds up, exactly as the Solidity does. Run with
--emit to regenerate the Solidity cases after touching the math on either side.
"""
import argparse
import random

BPS = 10_000
FEE_BPS = 300


def ceil_div(a, b):
    return -(-a // b)


class Curve:
    def __init__(self, P, T0):
        self.P, self.T, self.R = P, T0, 0
        self.k = P * T0

    def buy(self, quote_in):
        fee = quote_in * FEE_BPS // BPS
        net = quote_in - fee
        new_t = ceil_div(self.k, self.P + self.R + net)
        out = self.T - new_t if self.T > new_t else 0
        self.R += net
        self.T = new_t
        return net, out

    def sell(self, tokens_in):
        new_t = self.T + tokens_in
        new_q = ceil_div(self.k, new_t)
        gross = (self.P + self.R) - new_q if self.P + self.R > new_q else 0
        self.R -= gross
        self.T = new_t
        return gross


def emit(cases, path):
    lines = [
        "// SPDX-License-Identifier: MIT",
        "pragma solidity ^0.8.26;",
        "",
        "// GENERATED by scripts/curve_model.py -- do not edit by hand.",
        'import {Test} from "forge-std/Test.sol";',
        'import {CurveMath} from "../contracts/CurveMath.sol";',
        "",
        "contract CurveMathCasesTest is Test {",
    ]
    for i, (P, T0, ops) in enumerate(cases):
        c = Curve(P, T0)
        lines += [
            f"    function test_case{i}() public pure {{",
            f"        uint256 P = {P};",
            f"        uint256 T = {T0};",
            "        uint256 R = 0;",
            "        uint256 k = P * T;",
            "        uint256 out;",
        ]
        for kind, amt in ops:
            if kind == "buy":
                net, out = c.buy(amt)
                lines += [
                    f"        (out, T) = CurveMath.tokensOut(k, P + R, T, {net});",
                    f"        assertEq(out, {out});",
                    f"        R += {net};",
                ]
            else:
                gross = c.sell(amt)
                lines += [
                    f"        (out, T) = CurveMath.quoteOut(k, P + R, T, {amt});",
                    f"        assertEq(out, {gross});",
                    f"        R -= {gross};",
                ]
        lines += ["        assertGe((P + R) * T, k);", "    }", ""]
    lines.append("}")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")


def make_cases(seed=4663, n=12):
    rng = random.Random(seed)
    cases = []
    for _ in range(n):
        P = rng.choice([5 * 10**18, 5_000 * 10**18, 123_456 * 10**18])
        T0 = 10**27
        c = Curve(P, T0)
        held = 0
        ops = []
        for _ in range(rng.randint(3, 8)):
            if held > 0 and rng.random() < 0.4:
                amt = rng.randint(1, held)
                ops.append(("sell", amt))
                c.sell(amt)
                held -= amt
            else:
                amt = rng.randint(1, 20_000 * 10**18)
                _, out = c.buy(amt)
                ops.append(("buy", amt))
                held += out
        cases.append((P, T0, ops))
    return cases


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--emit", default="test/CurveMathCases.t.sol")
    a = ap.parse_args()
    emit(make_cases(), a.emit)
    print("wrote", a.emit)
